---
##
# Defaults for role xapi_bridge
#

xapi_bridge_user: xapi
xapi_bridge_user_group: adm  #perms on tracking.log
xapi_bridge_log_user: root
xapi_bridge_app_dir: "{{ COMMON_APP_DIR }}/xapi"
xapi_bridge_user_home: "{{ xapi_bridge_app_dir }}"
xapi_bridge_log_dir: "{{ COMMON_LOG_DIR }}/xapi"

xapi_bridge_repo: "https://github.com/raccoongang/edx-xapi-bridge"
xapi_bridge_venv_dir: "{{ xapi_bridge_app_dir }}/venvs/xapi"
xapi_bridge_venv_bin: "{{ xapi_bridge_venv_dir }}/bin"
xapi_bridge_code_dir: "{{ xapi_bridge_app_dir }}/edx-xapi-bridge"
xapi_bridge_version: "master"

xapi_bridge_service_name: xapi

# application settings defaults
xapi_PUBLISH_MAX_WAIT_TIME: 5
xapi_PUBLISH_MAX_PAYLOAD: 100
xapi_PUBLISH_MAX_RETRIES: 1
xapi_NOTIFIER_READ_FREQ: 5
xapi_NOTIFIER_POLL_TIMEOUT: 1000
xapi_LRS_ENDPOINT: "https://learninglocker.net/data/xAPI/"
xapi_LRS_USERNAME: "fakeuser"
xapi_LRS_PASSWORD: "fakepassword"
xapi_LRS_BASICAUTH_HASH: !!null
xapi_LRS_BACKEND_TYPE: "learninglocker"
xapi_OPENEDX_PLATFORM_URI: "http://127.0.0.1"
xapi_OPENEDX_OAUTH2_CLIENT_ID: "foo"
xapi_OPENEDX_OAUTH2_CLIENT_SECRET: "notasecret"
xapi_LMS_API_USE_MEMCACHED: false
xapi_MEMCACHED_ADDRESS: "127.0.0.1:11211"
xapi_IGNORED_EVENT_TYPES: []
xapi_SENTRY_DSN: !!null
xapi_HTTP_PUBLISH_STATUS: false
xapi_HTTP_PUBLISH_IP: "0.0.0.0"
xapi_HTTP_PUBLISH_PORT: 9090
xapi_DEBUG_MODE: false
xapi_EXCEPTIONS_NO_CONTINUE: false
xapi_TEST_LOAD_TRACKING_TOTAL_LOG_WRITES: 20
xapi_TEST_LOAD_SLEEP_SECS_BETWEEN_WRITES: 1
xapi_TEST_LOAD_SUCCESSFUL_STATEMENTS_BENCHMARK: 150
xapi_TEST_LOAD_TRACKING_FILE_SOURCE: "fixtures/test_loadtest_events_0.json"

supervisor_available_dir: "{{ supervisor_app_dir }}/conf.available.d"
supervisor_app_dir: "{{ COMMON_APP_DIR }}/supervisor"
supervisor_data_dir: "{{ COMMON_DATA_DIR }}/supervisor"
supervisor_service_user: "{{ common_web_user }}"
supervisor_log_dir: "{{ COMMON_LOG_DIR }}/supervisor"
supervisor_user: supervisor
common_web_user: www-data
supervisor_cfg_dir: "{{ supervisor_app_dir }}/conf.d"
supervisor_ctl: "/edx/bin/supervisorctl"
supervisor_cfg: "{{ supervisor_cfg_dir }}/xapi.conf"
